# Generated by Django 4.2.23 on 2025-07-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('money', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
